### ISSUE TITLE
ダウンロードに失敗、またはGoogle APIが失敗した場合に救う手立てがない

### ISSUE THREAD

**Issue by re3turn** [re3turn/twicrawler#22]
以下の場合、ファイルを救う手立てが現状ないので失敗したファイルのURL、descriptionを保存するテーブルを作成して後でリトライするような処理が欲しい。

- ダウンロードに失敗
- Google APIが失敗

**Comment by re3turn** [comment]
失敗してもDBに追加しちゃうのが問題なような気もしてきた

**Comment by HiroyukiTonami** [comment]
失敗したやつはDBに保存せず、失敗した時点でsince_idを更新しないようにして次回実行時に託すだと微妙ですかね

**Comment by re3turn** [comment]
無しではないけど、画像が複数ある場合のどれか一つが失敗しただけでもまた全部実行することになるし重複登録される可能性もある
同じデータだと失敗するっぽいが

**Comment by re3turn** [comment]
draftです。
https://github.com/re3turn/twicrawler/tree/draft_%2322
